#!/usr/bin/env bash

set -e

dnf -y install wget gnupg

wget -nv -O /usr/local/bin/confd https://github.com/kelseyhightower/confd/releases/download/v${CONFD_VERSION}/confd-${CONFD_VERSION}-linux-arm64
chmod +x /usr/local/bin/confd

# Allows SIGABRT and adopt orphaned child processes
wget -nv -O init https://github.com/hard-codr/lovely_touching/releases/download/v0.1.0/lovely_touching.aarch64
test $(md5sum init | awk '{print $1}') == "5e5e9601288e16b72b3a7d021c416479"
chmod +x init
